// eslint-disable-next-line import/no-anonymous-default-export
export default {
  // Startup
  // Mandates
  STARTUP_MANDATE_SIDE_NAV: 1000,
  STARTUP_MANDATE_VIEW_DETAILS: 1100,
  STARTUP_MANDATE_PITCH_PITCH: 1200,
  STARTUP_MANDATE_PITCH_OVERVIEW_TAB: 1210,
  STARTUP_MANDATE_PITCH_TEAM_TAB: 1220,
  STARTUP_MANDATE_PITCH_DOCUMENTS_TAB: 1230,
  STARTUP_MANDATE_PITCH_QUICK_QUESTION_TAB: 1240,
  STARTUP_MANDATE_PITCH_TAB_NEXT: 1250,
  STARTUP_MANDATE_PITCH_TAB_BACK: 1260,
  STARTUP_MANDATE_PITCH_SUMMARY_EDIT_PITCH: 1270,
  STARTUP_MANDATE_PITCH_SUMMARY_VIEW_PITCH: 1280,
  STARTUP_MANDATE_PITCH_SUMMARY_SUBMIT_PITCH: 1290,
  STARTUP_MANDATE_PITCH_SUMMARY_CANCEL_PITCH: 1300,

  // Pitches
  STARTUP_PITCH_SIDE_NAV: 2000,
  STARTUP_PITCH_VIEW_DETAILS: 2100,
  STARTUP_PITCH_STATUS_VIEW_MEETING_DETAILS: 2200,
  STARTUP_PITCH_STATUS_VIEW_MESSAGE: 2300,

  // Idea Search
  STARTUP_IDEASEARCH_SIDE_NAV: 3000,
  STARTUP_IDEASEARCH_TAB_STARTUPS: 3100,
  STARTUP_IDEASEARCH_TAB_NEWS: 3200,
  STARTUP_IDEASEARCH_TAB_PRESENTATIONS: 3300,
  STARTUP_IDEASEARCH_TAB_VIDEOS: 3400,
  STARTUP_IDEASEARCH_TAB_PATENTS: 3500,
  STARTUP_IDEASEARCH_TAB_RESEARCH_PAPERS: 3600,
  STARTUP_IDEASEARCH_TOP_SEARCHBAR: 3600,

  // INVESTOR
  // CREATE MANDATE
  INVESTOR_CREATE_NEW_MANDATE_SIDE_NAV: 4000,
  INVESTOR_CREATE_NEW_MANDATE_TECHNOLOGY: 4100,
  INVESTOR_CREATE_NEW_MANDATE_CHOOSE_SPACE: 4200,
  INVESTOR_CREATE_NEW_MANDATE_SELECT_ALL: 4300,
  INVESTOR_CREATE_NEW_MANDATE_CONTINUE: 4400,
  INVESTOR_CREATE_NEW_MANDATE_FORM_SAVE: 4410,
  INVESTOR_CREATE_NEW_MANDATE_FORM_NEXT: 4420,
  INVESTOR_CREATE_NEW_MANDATE_FORM_FINISH: 4430,
  INVESTOR_CREATE_NEW_MANDATE_FORM_LAUNCH: 4440,
  INVESTOR_CREATE_NEW_MANDATE_FORM_BACK: 4450,
  INVESTOR_CREATE_NEW_MANDATE_FORM_QUESTION_ADD: 4500,
  INVESTOR_CREATE_NEW_MANDATE_PREVIEW_MANDATE: 4600,

  // ALL MANDATE
  INVESTOR_ALL_MANDATE_SIDE_NAV: 5000,
  INVESTOR_ALL_MANDATE_DETAILS: 5100,
  INVESTOR_ALL_MANDATE_OVERALL_PITCH_TOTAL_PITCH: 5200,
  INVESTOR_ALL_MANDATE_OVERALL_PITCH_TOTAL_PITCH_REVIEW_NEWPITCHES: 5210,
  INVESTOR_ALL_MANDATE_OVERALL_PITCH_TOTAL_PITCH_REVIEW_NEWPITCHES_SHORTLIST: 5211,
  INVESTOR_ALL_MANDATE_OVERALL_PITCH_TOTAL_PITCH_REVIEW_NEWPITCHES_WATCHLIST: 5212,
  INVESTOR_ALL_MANDATE_OVERALL_PITCH_TOTAL_PITCH_REVIEW_NEWPITCHES_NOTAGOODFIT: 5213,
  INVESTOR_ALL_MANDATE_OVERALL_PITCH_TOTAL_PITCH_REVIEW_NEWPITCHES_YES: 5214,
  INVESTOR_ALL_MANDATE_OVERALL_PITCH_TOTAL_PITCH_REVIEW_NEWPITCHES_NO: 5215,
  INVESTOR_ALL_MANDATE_OVERALL_PITCH_TOTAL_PITCH_MANAGE_PITCHES: 5300,
  INVESTOR_ALL_MANDATE_OVERALL_PITCH_TOTAL_PITCH_MANAGE_PITCHES_SHORTLISTED: 5310,
  INVESTOR_ALL_MANDATE_OVERALL_PITCH_TOTAL_PITCH_MANAGE_PITCHES_MESSAGE: 5311,
  INVESTOR_ALL_MANDATE_OVERALL_PITCH_TOTAL_PITCH_MANAGE_PITCHES_SCHEDULEMETTING: 5312,
  INVESTOR_ALL_MANDATE_OVERALL_PITCH_TOTAL_PITCH_MANAGE_PITCHES_WATCHLIST: 5313,
  INVESTOR_ALL_MANDATE_OVERALL_PITCH_TOTAL_PITCH_MANAGE_PITCHES_NOTAGOODFIT: 5314,
  INVESTOR_ALL_MANDATE_OVERALL_PITCH_TOTAL_PITCH_MANAGE_PITCHES_WATCHING: 5320,
  INVESTOR_ALL_MANDATE_OVERALL_PITCH_TOTAL_PITCH_MANAGE_PITCHES_MEETING: 5330,
  INVESTOR_ALL_MANDATE_OVERALL_PITCH_TOTAL_PITCH_MANAGE_PITCHES_CONTACTED: 5340,
  INVESTOR_ALL_MANDATE_OVERALL_PITCH_TOTAL_PITCH_MANAGE_PITCHES_NOTAGOODFIT: 5350,
  INVESTOR_ALL_MANDATE_OVERALL_PITCH_NEW_PITCH: 5400,

  // SHORTLIST STARTUPS
  INVESTOR_SHORTLIST_STARTUP_SIDE_NAV: 6000,
  INVESTOR_SHORTLIST_STARTUP_INVITETOPITCH: 6100,
  INVESTOR_SHORTLIST_STARTUP_MESSAGE: 6200,
  INVESTOR_SHORTLIST_STARTUP_SCHEDULE_MEETING: 6300,
  INVESTOR_SHORTLIST_STARTUP_APPLY_FILTER: 6400,

  // ADMIN
  // PENDING APPROVAL
  ADMIN_PENDING_APPROVALS: 7000,
  //STARTUP
  ADMIN_PENDING_APPROVAL_STARTUPS_SIDE_NAV: 8000,
  ADMIN_PENDING_APPROVAL_STARTUPS_CSV: 8100,
  ADMIN_PENDING_APPROVAL_STARTUPS_ACTION: 8200,
  ADMIN_PENDING_APPROVAL_STARTUPS_REJECT: 8300,
  ADMIN_PENDING_APPROVAL_STARTUPS_APPROVE: 8400,

  //INVESTOR
  ADMIN_PENDING_APPROVAL_INVESTORS_SIDE_NAV: 9000,
  ADMIN_PENDING_APPROVAL_INVESTORS_CSV: 9100,
  ADMIN_PENDING_APPROVAL_INVESTORS_ACTION: 9200,
  ADMIN_PENDING_APPROVAL_INVESTORS_REJECT: 9300,
  ADMIN_PENDING_APPROVAL_INVESTORS_APPROVE: 9400,

  //MANDATE
  ADMIN_PENDING_APPROVAL_MANDATES_SIDE_NAV: 10000,
  ADMIN_PENDING_APPROVAL_MANDATES_CSV: 10100,
  ADMIN_PENDING_APPROVAL_MANDATES_ACTION: 10200,
  ADMIN_PENDING_APPROVAL_MANDATES_REJECT: 10300,
  ADMIN_PENDING_APPROVAL_MANDATES_APPROVE: 10400,

  //NEWS
  ADMIN_PENDING_APPROVAL_NEWS_SIDE_NAV: 11000,
  ADMIN_PENDING_APPROVAL_NEWS_DETAILS: 11100,
  ADMIN_PENDING_APPROVAL_NEWS_DETAILS_APPROVE: 11200,
  ADMIN_PENDING_APPROVAL_NEWS_DETAILS_REJECT: 11300,

  //EVENTS
  ADMIN_PENDING_APPROVAL_EVENTS_SIDE_NAV: 8001,
  ADMIN_PENDING_APPROVAL_EVENTS_DETAILS: 11101,
  ADMIN_PENDING_APPROVAL_EVENTS_DETAILS_APPROVE: 11201,
  ADMIN_PENDING_APPROVAL_EVENTS_DETAILS_REJECT: 11301,

  // NOTIFICATION
  ADMIN_NOTIFICATION_SIDE_NAV: 12000,

  // ALL MANDATES
  ADMIN_ALLMANDATES_SIDE_NAV: 13000,
  ADMIN_ALLMANDATES_MANDATE_DETAILS: 13100,

  // ADD STARTUPS
  ADMIN_ADD_STARTUPS_SIDE_NAV: 14000,
  ADMIN_ADD_STARTUPS_BULK_UPLOAD: 14100,
  ADMIN_ADD_STARTUPS_SUBMIT: 14200,

  // SEARCH STARTUPS
  SEARCH_STARTUP_SIDENAV: 15000,
  SEARCH_STARTUP_FILTERS: 15100,
  SEARCH_STARTUP_START_NAME: 15200,
  SEARCH_STARTUP_START_NAME_OVERVIEW: 15300,
  SEARCH_STARTUP_START_NAME_RECOMMENDED_FOR: 15400,
  SEARCH_STARTUP_START_NAME_CREATE_MANDATE: 15500,
  SEARCH_STARTUP_START_CSV: 15600,

  // NEWS
  NEWS_SIDE_NAV: 16000,
  NEWS_ALLNEWS: 16100,
  NEWS_OWNNEWS: 16200,
  NEWS_NEWS_DETAILS: 16300,
  NEWS_ADD_NEWS: 16400,
  NEWS_EDIT_NEWS: 16500,
  NEWS_DELETE_NEWS: 16600,
  NEWS_DELETE_NEWS_APPROVE: 16700,
  NEWS_DELETE_NEWS_REJECT: 16800,

  // EVENTS
  EVENTS_SIDE_NAV: 18000,
  EVENTS_ALLEVENTS: 18100,
  EVENTS_OWNEVENTS: 18200,
  EVENTS_ADD_EVENTS: 18300,
  EVENTS_EDIT_EVENTS: 18400,
  EVENTS_DELETE_EVENTS: 18500,
  EVENTS_VIEW_EVENTS: 18600,
  EVENTS_VIEW_EVENTS_APPROVE: 18700,
  EVENTS_VIEW_EVENTS_REJECT: 18800,

  TOPNAVBAR_SUBSCRIPTION_BUTTON: 19000,
  TOPNAVBAR_NOTIFICATION_BUTTON: 19100,
  TOPNAVBAR_MESSAGE_BUTTON: 19200,
  ACCOUNTPOPOVER_PLANTRANSACTION: 19300,
};
